###
GET http://localhost:3001

###
GET http://localhost:3001/api/tareas

###
POST http://localhost:3001/api/tareas
Content-Type: application/json

{
    "title": "Completada",
    "description" : "Descripcion 2",
    "fechaCreacion": 22,
    "fechaCompletado": 33,
    "fechaLimite": 44
}

###
GET  http://localhost:3001/api/tareas/62a8ad4a298c9484a9912d11

###
DELETE  http://localhost:3001/api/tareas/62aa28b58e9ae8e7c939b119

###
GET  http://localhost:3001/api/tareas/DoneTasks

###
PUT http://localhost:3001/api/tareas/62a8b929e593b717be3c727d
Content-Type: application/json

{
    "title" : "caminar"
}

###Get all personalizado
GET http://localhost:3001/api/tareas?size=2